=== otabuzzman/astrolabe/astrolabe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 sp2 U (http://www.altova.com) by Jürgen Schuck (MATERNA GmbH) -->
<xs:schema xmlns="http://www.cartacelestis.eu/astrolabe/model" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.cartacelestis.eu/astrolabe/model" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="AstrolabeType">
		<xs:sequence>
			<xs:element ref="Epoch"/>
			<xs:element ref="Chart" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional"/>
		<xs:attribute name="locale" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="([a-z][a-z])|([a-z][a-z]_[A-Z][A-Z])"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Astrolabe" type="AstrolabeType"/>
	<xs:complexType name="ChartType">
		<xs:sequence>
			<xs:element ref="Horizon" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional"/>
		<xs:attribute name="pagesize" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="a[0-6]|[0-9]+(\.[0-9]+)?x[0-9]+(\.[0-9]+)?"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="scale" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:double">
					<xs:minExclusive value="0"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="hemisphere" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="northern|southern"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Chart">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="ChartStereographic"/>
				<xs:element ref="ChartOrthographic"/>
				<xs:element ref="ChartEquidistant"/>
				<xs:element ref="ChartGnomonic"/>
				<xs:element ref="ChartEqualarea"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="ChartStereographic">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ChartType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="ChartOrthographic" type="ChartType"/>
	<xs:element name="ChartEquidistant" type="ChartType"/>
	<xs:element name="ChartGnomonic" type="ChartType"/>
	<xs:element name="ChartEqualarea" type="ChartType"/>
	<xs:complexType name="HorizonType">
		<xs:sequence>
			<xs:element ref="Latitude"/>
			<xs:element ref="Longitude" minOccurs="0"/>
			<xs:element ref="Date" minOccurs="0"/>
			<xs:element ref="Circle" maxOccurs="unbounded"/>
			<xs:element ref="BodyStellar" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional"/>
		<xs:attribute name="practicality" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="none|never|seldom|sometimes|frequent|always"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Horizon">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="HorizonLocal"/>
				<xs:element ref="HorizonEquatorial"/>
				<xs:element ref="HorizonEcliptical"/>
				<xs:element ref="HorizonGalactic"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="HorizonLocal">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="HorizonType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="HorizonEquatorial" type="HorizonType"/>
	<xs:element name="HorizonEcliptical">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="HorizonType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="HorizonGalactic" type="HorizonType"/>
	<xs:complexType name="CircleType">
		<xs:sequence>
			<xs:element ref="Angle"/>
			<xs:element ref="Begin"/>
			<xs:element ref="End"/>
			<xs:element ref="Dial" minOccurs="0"/>
			<xs:element ref="Annotation" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional"/>
		<xs:attribute name="importance" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="canonical|cardinal"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Circle">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="CircleParallel"/>
				<xs:element ref="CircleMeridian"/>
				<xs:element ref="CircleSouthernPolar"/>
				<xs:element ref="CircleNorthernPolar"/>
				<xs:element ref="CircleSouthernTropic"/>
				<xs:element ref="CircleNorthernTropic"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="MarkType">
		<xs:choice>
			<xs:element ref="Immediate"/>
			<xs:element ref="Reference"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="Begin" type="MarkType"/>
	<xs:element name="End" type="MarkType"/>
	<xs:complexType name="ReferenceType">
		<xs:attribute name="circle" type="xs:string" use="required"/>
		<xs:attribute name="node" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="chasing|leading"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Reference">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ReferenceType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Immediate" type="AngleType"/>
	<xs:element name="CircleParallel" type="CircleType"/>
	<xs:element name="CircleMeridian" type="CircleType"/>
	<xs:element name="CircleSouthernPolar">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="CircleType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="CircleNorthernPolar">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="CircleType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="CircleSouthernTropic">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="CircleType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="CircleNorthernTropic">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="CircleType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="DialType">
		<xs:sequence>
			<xs:element ref="GraduationSpan"/>
			<xs:element ref="GraduationHalf" minOccurs="0"/>
			<xs:element ref="GraduationFull" minOccurs="0"/>
			<xs:element ref="Annotation" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional"/>
		<xs:attribute name="baseline" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="none|line|rail"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="reflect" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:element name="Dial">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="DialDegree"/>
				<xs:element ref="DialHour"/>
				<xs:element ref="DialDay"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="DialDegree">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="DialType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="DialHour" type="DialType"/>
	<xs:element name="DialDay">
		<xs:annotation>
			<xs:documentation>Nur bei CircleParallel und HorizonEquatorial erlaubt.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="DialType">
					<xs:attribute name="sun" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:pattern value="apparent|mean|true"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="GraduationType">
		<xs:sequence>
			<xs:element ref="AnnotationStraight" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="span" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:double">
					<xs:minExclusive value="0"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="GraduationSpan">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="GraduationType">
					<xs:attribute name="division" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:positiveInteger">
								<xs:minInclusive value="1"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="GraduationHalf">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="GraduationType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="GraduationFull">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="GraduationType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="AnnotationType">
		<xs:sequence>
			<xs:element ref="Text" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional"/>
		<xs:attribute name="purpose" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="obscure|bodydescription|circledescription|dialdescription|dialnumber|dialsubnumber|guidance"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="anchor" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="topleft|topmiddle|topright|middleleft|middle|middleright|bottomleft|bottommiddle|bottomright"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="reverse" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:element name="Annotation">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="AnnotationStraight"/>
				<xs:element ref="AnnotationCurved"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="AnnotationStraight">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="AnnotationType">
					<xs:attribute name="radiant" type="xs:boolean" use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="AnnotationCurved">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="AnnotationType">
					<xs:attribute name="distance" type="xs:double" use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="TextType">
		<xs:sequence>
			<xs:element ref="Subscript" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="Superscript" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="value" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="Text" type="TextType"/>
	<xs:element name="Subscript" type="TextType"/>
	<xs:element name="Superscript" type="TextType"/>
	<xs:complexType name="GlyphType">
		<xs:sequence>
			<xs:element ref="Annotation" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional"/>
		<xs:attribute name="value" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="."/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="turn" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:double">
					<xs:minInclusive value="0"/>
					<xs:maxExclusive value="24"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="spin" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:double">
					<xs:maxInclusive value="0"/>
					<xs:minExclusive value="-24"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Glyph" type="GlyphType"/>
	<xs:complexType name="BodyStellarType">
		<xs:sequence>
			<xs:element ref="Position"/>
			<xs:element ref="Glyph"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:element name="BodyStellar" type="BodyStellarType"/>
	<xs:complexType name="BodyOrbitalType">
		<xs:sequence/>
		<xs:attribute name="name" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:element name="BodyOrbital" type="BodyOrbitalType"/>
	<!--Basistypen und -elemente-->
	<xs:complexType name="RationalType">
		<xs:attribute name="value" type="xs:double" use="required"/>
	</xs:complexType>
	<xs:element name="Rational" type="RationalType"/>
	<xs:element name="JD" type="RationalType">
		<xs:annotation>
			<xs:documentation>Julianischer Tag.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="r" type="RationalType"/>
	<xs:complexType name="DMSType">
		<xs:attribute name="deg" type="xs:integer" use="required"/>
		<xs:attribute name="min" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="0"/>
					<xs:maxExclusive value="60"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="sec" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:double">
					<xs:minInclusive value="0.0"/>
					<xs:maxExclusive value="60.0"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="DMS" type="DMSType"/>
	<xs:complexType name="HMSType">
		<xs:attribute name="hrs" type="xs:integer" use="required"/>
		<xs:attribute name="min" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="0"/>
					<xs:maxExclusive value="60"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="sec" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:double">
					<xs:minInclusive value="0.0"/>
					<xs:maxExclusive value="60.0"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="HMS" type="HMSType"/>
	<xs:complexType name="YMDType">
		<xs:attribute name="y" type="xs:integer" use="required"/>
		<xs:attribute name="m" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="1"/>
					<xs:maxInclusive value="13"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="d" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="1"/>
					<xs:maxInclusive value="31"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="YMD" type="YMDType"/>
	<xs:complexType name="AngleType">
		<xs:choice>
			<xs:element ref="DMS"/>
			<xs:element ref="Rational"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="Angle" type="AngleType">
		<xs:annotation>
			<xs:documentation>Azimut bei CircleMeridian, Höhe bei CircleParallel.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="Latitude" type="AngleType">
		<xs:annotation>
			<xs:documentation>Nur bei HorizonLocal relevant.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="Longitude" type="AngleType">
		<xs:annotation>
			<xs:documentation>Nur bei HorizonLocal relevant.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="HA" type="TimeType">
		<xs:annotation>
			<xs:documentation>Stundenwinkel.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="phi" type="AngleType"/>
	<xs:element name="theta" type="AngleType"/>
	<xs:complexType name="TimeType">
		<xs:choice>
			<xs:element ref="HMS"/>
			<xs:element ref="Rational"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="Time" type="TimeType">
		<xs:annotation>
			<xs:documentation>UTC</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="DateType">
		<xs:choice>
			<xs:element ref="Calendar"/>
			<xs:element ref="JD"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="Date" type="DateType"/>
	<xs:element name="Epoch">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="DateType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="CalendarType">
		<xs:sequence>
			<xs:element ref="YMD"/>
			<xs:element ref="Time" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Calendar" type="CalendarType"/>
	<xs:complexType name="CartesianType">
		<xs:attribute name="x" type="xs:double" use="required"/>
		<xs:attribute name="y" type="xs:double" use="required"/>
		<xs:attribute name="z" type="xs:double" use="optional"/>
	</xs:complexType>
	<xs:element name="Cartesian" type="CartesianType"/>
	<xs:complexType name="PolarType">
		<xs:sequence>
			<xs:element ref="phi"/>
			<xs:element ref="r" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Polar" type="PolarType"/>
	<xs:complexType name="SphericalType">
		<xs:sequence>
			<xs:element ref="phi"/>
			<xs:element ref="theta"/>
			<xs:element ref="r" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Spherical" type="SphericalType"/>
	<xs:element name="Position" type="SphericalType"/>
</xs:schema>

=== otabuzzman/astrolabe/astrolabe.xml
<?xml version="1.0" encoding="UTF-8"?>
<Astrolabe xmlns="http://www.cartacelestis.eu/astrolabe/model"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cartacelestis.eu/astrolabe/model
astrolabe.xsd">
	<Date>
		<DateOccidental>
			<YMD y="2000" m="1" d="1" />
		</DateOccidental>
	</Date>
	<Chart>
		<ChartStereographic pagesize="a4" hemisphere="northern">
			<!--eqp-24.5-->
			<Horizon>
				<HorizonEquatorial practicality="none">
					<Latitude>
						<Rational value="0.0" />
					</Latitude>
					<Circle>
						<CircleParallel name="eqp-24.5"
							importance="canonical">
							<Angle>
								<Rational value="-24.5" />
							</Angle>
							<Begin>
								<Immediate>
									<Rational value="0" />
								</Immediate>
							</Begin>
							<End>
								<Immediate>
									<Rational value="360" />
								</Immediate>
							</End>
						</CircleParallel>
					</Circle>
				</HorizonEquatorial>
			</Horizon>
			<!--galactic-->
			<Horizon>
				<HorizonGalactic practicality="seldom">
					<Latitude>
						<DMS min="0" sec="0.0" deg="0" />
					</Latitude>
					<Circle>
						<CircleParallel importance="canonical">
							<Angle>
								<Rational value="-80" />
							</Angle>
							<Begin>
								<Reference circle="eqp-24.5"
									node="chasing" />
							</Begin>
							<End>
								<Reference circle="eqp-24.5"
									node="leading" />
							</End>
						</CircleParallel>
					</Circle>
					<Circle>
						<CircleParallel importance="canonical">
							<Angle>
								<Rational value="-60" />
							</Angle>
							<Begin>
								<Reference circle="eqp-24.5"
									node="chasing" />
							</Begin>
							<End>
								<Reference circle="eqp-24.5"
									node="leading" />
							</End>
						</CircleParallel>
					</Circle>
					<Circle>
						<CircleParallel importance="canonical">
							<Angle>
								<Rational value="-40" />
							</Angle>
							<Begin>
								<Reference circle="eqp-24.5"
									node="chasing" />
							</Begin>
							<End>
								<Reference circle="eqp-24.5"
									node="leading" />
							</End>
						</CircleParallel>
					</Circle>
					<Circle>
						<CircleParallel importance="canonical">
							<Angle>
								<Rational value="-20" />
							</Angle>
							<Begin>
								<Reference circle="eqp-24.5"
									node="chasing" />
							</Begin>
							<End>
								<Reference circle="eqp-24.5"
									node="leading" />
							</End>
						</CircleParallel>
					</Circle>
					<!--horizon-->
					<Circle>
						<CircleParallel importance="cardinal">
							<Angle>
								<Rational value="0.0" />
							</Angle>
							<Begin>
								<Reference circle="eqp-24.5"
									node="chasing" />
							</Begin>
							<End>
								<Reference circle="eqp-24.5"
									node="leading" />
							</End>
							<Dial>
								<DialAngle baseline="none"
									reflect="false">
									<GraduationSpan span="10"
										division="1">
										<AnnotationStraight
											purpose="dialsubnumber" anchor="middleleft" radiant="false"
											reverse="false">
											<Text
												value="@{dialdeg}@&#x00b0;" />
										</AnnotationStraight>
									</GraduationSpan>
									<Annotation>
										<AnnotationCurved
											purpose="dialdescription" anchor="bottomleft" radiant="false"
											reverse="false" distance="18.5">
											<Text
												value="Galaktische L&#x00e4;nge (&#x0394;l 10&#x00b0;)" />
										</AnnotationCurved>
									</Annotation>
								</DialAngle>
							</Dial>
						</CircleParallel>
					</Circle>
					<Circle>
						<CircleParallel importance="canonical">
							<Angle>
								<Rational value="20" />
							</Angle>
							<Begin>
								<Reference circle="eqp-24.5"
									node="leading" />
							</Begin>
							<End>
								<Reference circle="eqp-24.5"
									node="chasing" />
							</End>
						</CircleParallel>
					</Circle>
					<Circle>
						<CircleParallel importance="canonical">
							<Angle>
								<Rational value="40" />
							</Angle>
							<Begin>
								<Immediate>
									<Rational value="0.0" />
								</Immediate>
							</Begin>
							<End>
								<Immediate>
									<Rational value="360" />
								</Immediate>
							</End>
						</CircleParallel>
					</Circle>
					<Circle>
						<CircleParallel importance="canonical">
							<Angle>
								<Rational value="60" />
							</Angle>
							<Begin>
								<Immediate>
									<Rational value="0.0" />
								</Immediate>
							</Begin>
							<End>
								<Immediate>
									<Rational value="360" />
								</Immediate>
							</End>
						</CircleParallel>
					</Circle>
					<Circle>
						<CircleParallel importance="canonical">
							<Angle>
								<Rational value="80" />
							</Angle>
							<Begin>
								<Immediate>
									<Rational value="0.0" />
								</Immediate>
							</Begin>
							<End>
								<Immediate>
									<Rational value="360" />
								</Immediate>
							</End>
						</CircleParallel>
					</Circle>
					<!--meridians-->
					<Circle>
						<CircleMeridian importance="canonical">
							<Angle>
								<Rational value="0.0" />
							</Angle>
							<Begin>
								<Reference circle="eqp-24.5"
									node="leading" />
							</Begin>
							<End>
								<Immediate>
									<DMS deg="85" min="0" sec="0.0" />
								</Immediate>
							</End>
						</CircleMeridian>
					</Circle>
					<Circle>
						<CircleMeridian importance="canonical">
							<Angle>
								<Rational value="30" />
							</Angle>
							<Begin>
								<Reference circle="eqp-24.5"
									node="leading" />
							</Begin>
							<End>
								<Immediate>
									<DMS deg="85" min="0" sec="0.0" />
								</Immediate>
							</End>
						</CircleMeridian>
					</Circle>
					<Circle>
						<CircleMeridian importance="canonical">
							<Angle>
								<Rational value="60" />
							</Angle>
							<Begin>
								<Reference circle="eqp-24.5"
									node="leading" />
							</Begin>
							<End>
								<Immediate>
									<DMS deg="85" min="0" sec="0.0" />
								</Immediate>
							</End>
						</CircleMeridian>
					</Circle>
					<Circle>
						<CircleMeridian importance="canonical">
							<Angle>
								<Rational value="90" />
							</Angle>
							<Begin>
								<Immediate>
									<DMS deg="-85" min="0" sec="0.0" />
								</Immediate>
							</Begin>
							<End>
								<Immediate>
									<DMS deg="85" min="0" sec="0.0" />
								</Immediate>
							</End>
						</CircleMeridian>
					</Circle>
					<Circle>
						<CircleMeridian importance="canonical">
							<Angle>
								<Rational value="120" />
							</Angle>
							<Begin>
								<Immediate>
									<DMS deg="-85" min="0" sec="0.0" />
								</Immediate>
							</Begin>
							<End>
								<Immediate>
									<DMS deg="85" min="0" sec="0.0" />
								</Immediate>
							</End>
						</CircleMeridian>
					</Circle>
					<Circle>
						<CircleMeridian importance="canonical">
							<Angle>
								<Rational value="150" />
							</Angle>
							<Begin>
								<Immediate>
									<DMS deg="-85" min="0" sec="0.0" />
								</Immediate>
							</Begin>
							<End>
								<Immediate>
									<DMS deg="85" min="0" sec="0.0" />
								</Immediate>
							</End>
						</CircleMeridian>
					</Circle>
					<Circle>
						<CircleMeridian importance="canonical">
							<Angle>
								<Rational value="180" />
							</Angle>
							<Begin>
								<Reference circle="eqp-24.5"
									node="chasing" />
							</Begin>
							<End>
								<Immediate>
									<DMS deg="85" min="0" sec="0.0" />
								</Immediate>
							</End>
							<Dial>
								<DialAngle baseline="none"
									reflect="false">
									<GraduationSpan span="20"
										division="1">
										<AnnotationStraight
											purpose="guidance" anchor="topleft" radiant="false"
											reverse="false">
											<Text
												value="@{dialdeg}@&#x00b0;" />
										</AnnotationStraight>
									</GraduationSpan>
									<Annotation>
										<AnnotationCurved
											purpose="guidance" anchor="middleleft" radiant="false"
											reverse="false" distance="12">
											<Text
												value="Galaktische Breite (&#x0394;b 20&#x00b0;)" />
										</AnnotationCurved>
									</Annotation>
								</DialAngle>
							</Dial>
						</CircleMeridian>
					</Circle>
					<Circle>
						<CircleMeridian importance="canonical">
							<Angle>
								<Rational value="210" />
							</Angle>
							<Begin>
								<Reference circle="eqp-24.5"
									node="leading" />
							</Begin>
							<End>
								<Immediate>
									<DMS deg="85" min="0" sec="0.0" />
								</Immediate>
							</End>
						</CircleMeridian>
					</Circle>
					<Circle>
						<CircleMeridian importance="canonical">
							<Angle>
								<Rational value="240" />
							</Angle>
							<Begin>
								<Reference circle="eqp-24.5"
									node="leading" />
							</Begin>
							<End>
								<Immediate>
									<DMS deg="85" min="0" sec="0.0" />
								</Immediate>
							</End>
						</CircleMeridian>
					</Circle>
					<Circle>
						<CircleMeridian importance="canonical">
							<Angle>
								<Rational value="270" />
							</Angle>
							<Begin>
								<Reference circle="eqp-24.5"
									node="leading" />
							</Begin>
							<End>
								<Immediate>
									<DMS deg="85" min="0" sec="0.0" />
								</Immediate>
							</End>
						</CircleMeridian>
					</Circle>
					<Circle>
						<CircleMeridian importance="canonical">
							<Angle>
								<Rational value="300" />
							</Angle>
							<Begin>
								<Reference circle="eqp-24.5"
									node="leading" />
							</Begin>
							<End>
								<Immediate>
									<DMS deg="85" min="0" sec="0.0" />
								</Immediate>
							</End>
						</CircleMeridian>
					</Circle>
					<Circle>
						<CircleMeridian importance="canonical">
							<Angle>
